# prometheus/prometheus.yml

global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: kafka
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      # - targets: ["kafka-1:9200", "kafka-2:9200", "kafka-3:9200"]
      - targets:
        - "TAILSCALE_IP:9200"
        labels:
          env: "test"

  # - job_name: kafka-schema-registry
  #   scrape_interval: 30s
  #   scrape_timeout: 30s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     # - targets: ["schema-registry:9200"]
  #     - targets:
  #       - "TAILSCALE_IP:9203"

  # - job_name: kafka-connect
  #   scrape_interval: 30s
  #   scrape_timeout: 30s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     # - targets: ["connect:9200"]
  #     - targets:
  #       - "TAILSCALE_IP:9204"
