dashboard:
  enabled: true
service:
  enabled: true
  ## -- Single service is using `MixedProtocolLBService` feature gate.
  ## -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-1.2.3.4"
  # -- Additional annotations for TCP service only
  annotationsTCP: {}
  # -- Additional annotations for UDP service only
  annotationsUDP: {}
  # -- Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  # -- Additional entries here will be added to the service spec.
  # -- Cannot contain type, selector or ports entries.
  spec:
    loadBalancerIP: "TAILSCALE_IP"
  loadBalancerSourceRanges: []
  externalIPs:
    - TAILSCALE_IP
  additionalServices: {}
ports:
  traefik:
    expose:
      default: true
    port: 9000
    protocol: TCP
  dns-tcp:
    expose:
      default: true
    port: 53
    protocol: TCP
  dns-udp:
    expose:
      default: true
    port: 53
    protocol: UDP
# additionalArguments:
  # - --providers.file.filename=~/.kube/custom_configs/traefik-config.yaml
