apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo
   namespace: default
spec:
   replicas: 2
   selector:
      matchLabels:
         bb: web
   strategy:
    type: Recreate
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: bb-site
              image: vincetran96/getting-started
              imagePullPolicy: Always
