services:
  prometheus:
    image: prom/prometheus:v2.47.2
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: always
    ports:
      - "19093:9093"

  grafana:
    image: grafana/grafana:10.4.5
    restart: always
    ports:
      - "63000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-data:
