# Source: https://github.com/nextcloud/all-in-one/blob/main/compose.yaml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "60081:8080"
    environment:
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy
      APACHE_IP_BINDING: 127.0.0.1 # Should be set when running behind a web server or reverse proxy
      NEXTCLOUD_DATADIR: "/home/USERNAME/data/nextcloud"
      SKIP_DOMAIN_VALIDATION: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
